server:
  error:
    include-stacktrace: on_param
  tomcat:
    accesslog:
      enabled: true
spring:
  datasource:
    url: jdbc:postgresql://dpg-cigeip59aq012ev6gqsg-a.oregon-postgres.render.com:5432/receiteme
    username: receitemeusername
    password: 6tzBvkNpRshQpGAGLC4YpCYMC9bsymli
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

