spring:
  datasource:
    url: jdbc:postgresql://silly.db.elephantsql.com:5432/uwqshsfe
    username: uwqshsfe
    password: 5mviWguVG3lLs6rQplsGpU84x_M9p06V
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
