spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/receiteme_edmw
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  tomcat.accesslog.enabled: true
