spring:
  datasource:
    url: jdbc:postgresql://dpg-cknbtjiv7m0s73e1r9j0-a/receiteme_qc14
    username: receitemeusername
    password: Rehyk80NiiYTEzUw8tvotff8eYAWXUcj
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
