spring:
  datasource:
    url: jdbc:postgresql://dpg-cklcuj3j89us73dv9qbg-a.oregon-postgres.render.com:5432/receiteme_edmw
    username: receitemeusername
    password: bd07UcI5A7wIJ19SdiYaNxUPvl5McxJc
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: receite.me.app@gmail.com
    password: vosxbvsnnghydtgr
    protocol: smtp
    properties.mail.smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
