spring:
  datasource:
    url: jdbc:postgresql://db.qsiyobeencyejkwvmurr.supabase.co:5432/postgres
    username: postgres
    password: mgNDmGF12lJkl8bn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: receite.me.app@gmail.com
    password: vosxbvsnnghydtgr
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
